version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: "no"  # No reiniciar automáticamente
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: CarnetDB
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql  # Datos en memoria temporal