version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123
      - SA_USER=SA
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/sql
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 20 && 
        /opt/mssql-tools/bin/sqlcmd -S localhost -U ${SA_USER} -P ${SA_PASSWORD} -i /sql/init.sql
      "
